name: Closet-Server

on: push

jobs:
  - type: "SSH_COMMAND"
    working_directory: "/"
    login: "closetserver"
    password: "$closetserver"
    host: "20.204.52.137"
    port: "22"
    ignore_errors: true
    shell: "SH"
    run_as_script: true
